<img src="mioti.png" style="height: 100px">
<center style="color:#888">Data Science with Python </center>

# DSPy1. NumPy basics

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Sistema-de-paquetes-y-entornos-virtuales." data-toc-modified-id="Sistema-de-paquetes-y-entornos-virtuales.-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Sistema de paquetes y entornos virtuales.</a></span></li><li><span><a href="#Entorno-virtual" data-toc-modified-id="Entorno-virtual-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Entorno virtual</a></span></li><li><span><a href="#NumPy-basics" data-toc-modified-id="NumPy-basics-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>NumPy basics</a></span><ul class="toc-item"><li><span><a href="#ndarray:-n-dimensional-array-object" data-toc-modified-id="ndarray:-n-dimensional-array-object-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>ndarray: n-dimensional array object</a></span></li><li><span><a href="#dtype" data-toc-modified-id="dtype-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>dtype</a></span></li><li><span><a href="#Creación-de-arrays" data-toc-modified-id="Creación-de-arrays-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Creación de arrays</a></span></li><li><span><a href="#Basic-indexing-y-slicing" data-toc-modified-id="Basic-indexing-y-slicing-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Basic indexing y slicing</a></span></li><li><span><a href="#Operaciones-entre-arrays:-element-wise" data-toc-modified-id="Operaciones-entre-arrays:-element-wise-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Operaciones entre arrays: element-wise</a></span></li></ul></li></ul></div>

## Sistema de paquetes y entornos virtuales. 

Aparte de la funcionalidad básica del lenguaje (tipos básicos de datos, operaciones sobre los mismos, etc.), el software escrito en Python se organiza en módulos (ficheros), que a su vez se agrupan en paquetes (directorios). 



In [1]:
import datetime
now_time = datetime.datetime.now()
print(now_time)

2020-02-11 18:47:20.401696


Existen distintas distribuciones de Python que reunen distintos conjuntos de estos paquetes (amén de otro software, e.g., entornos de desarrollo como Jupyter notebooks).
<img src="anaconda_logo.png" style="height: 200px">
> The Most Popular Python Data Science Platform

>Anaconda Distribution is a free, easy-to-install **package manager**, environment manager and Python distribution with a collection of 1,000+ open source packages with free community support.


El gestor de paquetes se llama `conda`. 

## Entorno virtual

¿Qué ocurre si estamos trabajando en dos proyectos y cada uno necesita una versión diferente de un paquete?

<img src="conda.png" style="height: 300px">

Podemos tener interpretes de Python con distintos paquetes, aislados unos de otros, y usar el que nos convenga en un Jupyter notebook.

<div class="alert alert-block alert-success">
    
**TIP** Instalemos `nb-contrib-extensions`:
```
conda install -c conda-forge jupyter_contrib_nbextensions
```
</div>

## NumPy basics

<img src="numpy_logo.png" style="height: 100px">

NumPy viene de "Numerical Python": librería para computación numérica. 
* Diseñado para ser eficiente en operaciones con grandes volúmenes de datos
* Nos permite una sintaxis vectorial -> álgebra lineal  

Quizá no la usemos directamente de manera usual, pero es el fundamento sobre el que funcionan las librerías de Data Science en Python.

### ndarray: n-dimensional array object
<img src="ndarray.png" style="height: 300px">


In [2]:
import numpy as np
array_1d = np.array([7,2,9,10])
array_1d

array([ 7,  2,  9, 10])

In [ ]:
array_1d.shape

`array_1d` en este caso es de una única dimensión. Pero no es "fila" ni columna...

In [ ]:
array_2d_1d = np.array([[7,2,9,1]])
array_2d_1d

In [ ]:
array_2d_1d.shape

In [ ]:
array_2d = np.array([[5.2, 3.0, 4.5],
                     [9.1, 0.1, 0.3]])
array_2d

In [ ]:
array_2d.shape

In [ ]:
array_3d = np.array(
    [
        [
            [ 1,  2],
            [ 4,  3],
            [ 7,  4]
        ],
        [
            [ 2,  0],
            [ 9,  0],
            [ 7,  5]
        ],
        [
            [ 1,  0],
            [ 3,  0],
            [ 0,  2]
        ],
        [
            [ 9,  0],
            [ 6,  0],
            [ 9,  8]
        ]
    ]
)
print(array_3d)

In [ ]:
array_3d.shape

### dtype

Los arrays de NumPy son homogéneos: todos sus elementos han de tener el mismo tipo.

In [ ]:
array_int = np.array([7,2,9,10])
array_int.dtype

**Pregunta:** ¿Qué ocurrirá aquí?

In [ ]:
array_example = np.array([2,3,4.4,2])
array_example.dtype

In [ ]:
array_mixed = np.array(["hola", "caracola", 3.4])
array_mixed.dtype

Podemos fijar nosotros el tipo:

In [ ]:
arr_string = np.array([1.25, -9.6, 42], dtype=np.string_)
arr_string

O hacer conversiones explícitas:

In [ ]:
arr_string.astype(float)

**Pregunta:** ¿Qué devolverá el siguiente código?

In [ ]:
arr_string.astype(float)
arr_string.dtype









<div class="alert alert-block alert-danger">
    
**WARNING.** `dtype` devuelve siempre una copia de los datos, incluso aunque el nuevo tipo sea el mismo.

</div>

In [ ]:
arr_float = arr_string.astype(float)
arr_float.dtype

**Pregunta:** ¿Qué imprimiran los siguientes códigos?

In [ ]:
list_bool = [True, False, False]
for index, elem in enumerate(list_bool):
    if elem is True:
        print("Elem #{} is True".format(index))
    else:
        print("Elem #{} is False".format(index))

In [ ]:
arr_bool = np.array([True, False, False])
for index, elem in enumerate(arr_bool):
    if elem == True:
        print("Elem #{} is True".format(index))
    else:
        print("Elem #{} is False".format(index))

In [ ]:
arr_bool = np.array([True, False, False])
for index, elem in enumerate(arr_bool):
    if elem:
        print("Elem #{} is True".format(index))
    else:
        print("Elem #{} is False".format(index))

<div class="alert alert-block alert-danger">
    
**WARNING.** NumPy implementa su propio tipo bool por razones de eficiencia... ¡Nunca uses `is` en comparaciones booleanas!

</div>

### Creación de arrays

Además de con literales, como hemos visto, hay una serie de funciones que nos pueden venir bien para inicializar arrays:

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.randn(3,4)

### Basic indexing y slicing

Misma sintaxis que en los objetos de Python, pero n-dimensional

In [ ]:
arr = np.arange(0,9)
arr

Ejemplos:

In [ ]:
arr[0]

In [ ]:
arr[-1]

In [ ]:
arr[0:3]

In [ ]:
arr[0:8:2]

In [3]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr[2,2]

8

<img src="index.png" style="height: 400px">


In [ ]:
arr[0:2, 0:2]

In [5]:
arr[0:2, -1]

array([2, 5])

**Pregunta:** Dado el siguiente código:

In [ ]:
py_list = [1,2,3,4]
list_slice = py_list
list_slice

In [ ]:
list_slice[0] = 0
list_slice

¿Qué contendrá `py_list`?

In [ ]:
py_list

**Pregunta:** Dado el siguiente código:

In [ ]:
py_list = [1,2,3,4]
list_slice = py_list[0:2]
list_slice

In [ ]:
list_slice[0] = 0
list_slice

¿Qué contendrá `py_list`?

In [ ]:
py_list

**Pregunta:** Dado el siguiente código:
        

In [ ]:
np_arr = np.array([1,2,3,4])
np_slice = np_arr[0:2]
np_slice

In [ ]:
np_slice[0] = 0
np_slice

¿Qué contendrá `np_arr`?

In [ ]:
np_arr

<div class="alert alert-block alert-danger">

**WARNING.** El slicing de arrays de NumPy, a diferencia de las listas de Python devuelve _vistas_ de los datos y no copias. 

</div>

### Operaciones entre arrays: element-wise

Al contrario que en Python:

In [ ]:
lista1 = [1,2,3]
lista1 + lista1











Las operaciones entre arrays del mismo tamaño suceden elemento a elemento



In [ ]:
arr = np.array([1, 2, 3])
arr + arr

In [ ]:
arr * arr

In [ ]:
arr = np.array([2, 3, 5, 8, 1])
arr > 3

Las operaciones con escalares propagan el escalar a cada elemento del array:

In [ ]:
arr * 2

Y se pueden hacer operaciones entre arrays de distinto tamaño gracias al _broadcasting_

**Pregunta:** ¿Qué ocurrirá con los siguientes códigos?

In [ ]:
list_numbers = [0,1,2,3,4]
list_numbers[0:4] = 0
list_numbers

In [ ]:
arr_numbers = np.array([0,1,2,3,4])
arr_numbers[0:4] = 0
arr_numbers








En NumPy, en una asignación, el valor de un escalar también se propaga elemento a elemento 